name: ZenonApp
description: "Aplicación de gestión de granjas avícolas."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  lottie: ^2.2.0
  path_provider: ^2.1.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/zenonapp_icon.png"
  remove_alpha_ios: true
